---
abstract: 'Database::Migrator implementation for MySQL'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120900'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Database-Migrator-mysql
requires:
  DBD::mysql: 0
  DBI: 0
  Database::Migrator::Core: 0
  Database::Migrator::Types: 0
  File::Slurp: 0
  IPC::Run3: 0
  Moose: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Database-Migrator-mysql
  repository: git://git.urth.org/Database-Migrator-mysql.git
version: 0.01
